from:
  version: v2
  driver: mongodb
  source: mongodb://127.0.0.1:27017
to:
  version: v2
  driver: postgres
  source: host=localhost port=5432 user=postgres dbname=eiblog sslmode=disable password=MTI3LjAuMC4x
