name: release & package

on: push

jobs:
  package:
    runs-on: ubuntu-16.04
    steps:
    - name: Golang env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache mod
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Package tar
      run: dist.sh
    - name: Release push
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          *.tar.gz
